//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Course
    {
        public int Id { get; set; }
        public string Account { get; set; }
        public string C_Id { get; set; }
        public System.DateTime Date { get; set; }
        public string P_Name { get; set; }
        public string Part { get; set; }
        public Nullable<int> Series { get; set; }
        public Nullable<int> Times { get; set; }
        public Nullable<int> Power { get; set; }
        public Nullable<bool> Complete { get; set; }
    }
}
