//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStatus
    {
        public string Account { get; set; }
        public string C_Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Photo { get; set; }
        public double Height { get; set; }
        public double Weight { get; set; }
        public double Bodyfat { get; set; }
        public double BMR { get; set; }
        public double Balance { get; set; }
        public double Strength { get; set; }
        public double Endurance { get; set; }
        public double Effect { get; set; }
        public double Bodyrate { get; set; }
        public double Burden { get; set; }
        public Nullable<double> Rank { get; set; }
    }
}
