//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHabit
    {
        public string Account { get; set; }
        public string Control { get; set; }
        public string Fruit { get; set; }
        public string Ability { get; set; }
        public string Ontime { get; set; }
        public string Fry { get; set; }
        public string Drink { get; set; }
        public string Quality { get; set; }
        public string Sportnum { get; set; }
        public string Sporttime { get; set; }
        public string Sports { get; set; }
        public string Motivation { get; set; }
        public string Grade { get; set; }
        public string Place { get; set; }
        public string Look { get; set; }
        public string Want { get; set; }
        public string Request { get; set; }
        public string Increase { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
