//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usertest
    {
        public string Account { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public System.DateTime Birth { get; set; }
        public int Age { get; set; }
        public string Blood { get; set; }
        public double Height { get; set; }
        public double Weight { get; set; }
        public double Bodyfat { get; set; }
        public double BMR { get; set; }
        public string Disease { get; set; }
        public string History { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Job { get; set; }
        public string Sportnum { get; set; }
        public string Sporttime { get; set; }
        public string Sports { get; set; }
        public string Warmup { get; set; }
        public string Interest { get; set; }
        public string Place { get; set; }
        public string Motivation { get; set; }
        public string Purpose { get; set; }
        public string Want { get; set; }
        public string Request { get; set; }
        public string Quality { get; set; }
        public string Hobby { get; set; }
        public string Fry { get; set; }
        public string Drink { get; set; }
        public string Ontime { get; set; }
        public string Increase { get; set; }
        public bool IsAdmin { get; set; }
    }
}
